C   GMIN: A program for finding global minima
C   Copyright (C) 1999-2006 David J. Wales
C   This file is part of GMIN.
C
C   GMIN is free software; you can redistribute it and/or modify
C   it under the terms of the GNU General Public License as published by
C   the Free Software Foundation; either version 2 of the License, or
C   (at your option) any later version.
C
C   GMIN is distributed in the hope that it will be useful,
C   but WITHOUT ANY WARRANTY; without even the implied warranty of
C   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
C   GNU General Public License for more details.
C
C   You should have received a copy of the GNU General Public License
C   along with this program; if not, write to the Free Software
C   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
C
C
C
C   These dummy functions are listed here so GMIN can be compiled without CHARMM
C

      SUBROUTINE TAKESTEPCH(NP)
      IMPLICIT NONE
      INTEGER NP

      RETURN
      END

      SUBROUTINE READREF
      IMPLICIT NONE
      RETURN
      END

      SUBROUTINE TWISTCH(IICD,ANGLESTEP)
      IMPLICIT NONE
      INTEGER IICD
      DOUBLE PRECISION ANGLESTEP

      RETURN
      END

      SUBROUTINE TWISTDIHE(X,Y,Z,DMODE,DPERT)
      IMPLICIT NONE
      DOUBLE PRECISION  X(*),Y(*),Z(*)
      DOUBLE PRECISION DPERT
      INTEGER DMODE

      RETURN
      END

      SUBROUTINE REBUILD(X,Y,Z,I)
      IMPLICIT NONE
      DOUBLE PRECISION  X(*),Y(*),Z(*)
      INTEGER I

      RETURN
      END

      SUBROUTINE EICCH(IICD,ACOM,QADD,LENIC,INTLEN,IUNIC,
     &  TYPE,IBASE,SEGID,RESID,NICTOT,NSEG,RES,NATOM,ISLCT,
     &  B1IC,B2IC,T1IC,T2IC,PIC,IAR,JAR,KAR,LAR,TAR)
      IMPLICIT NONE

      INTEGER LENIC,INTLEN,IUNIC,IICD
      CHARACTER(LEN=4) SEGID(*),RESID(*),TYPE(*),RES(*)
      INTEGER IBASE(*),NICTOT(*)
      INTEGER NSEG,NATOM,ISLCT(*)
      DOUBLE PRECISION B1IC(*),B2IC(*),T1IC(*),T2IC(*),PIC(*)
      INTEGER  IAR(*),JAR(*),KAR(*),LAR(*)
      LOGICAL TAR(*)
      DOUBLE PRECISION ACOM
      LOGICAL QADD

      RETURN
      END

      SUBROUTINE PERTDIHE(X,Y,Z,CHPMIN,CHPMAX,CHNMIN,CHNMAX,ISEED)
      IMPLICIT NONE
      DOUBLE PRECISION X(*),Y(*),Z(*)
      DOUBLE PRECISION    CHPMIN,CHPMAX,CHNMIN,CHNMAX
      INTEGER             ISEED

      RETURN
      END

      SUBROUTINE GETRESNUM(JAR,IBASE,NRES,RESNUM,I)
      IMPLICIT NONE
      INTEGER NRES, RESNUM, I, JAR(*), IBASE(*)

      RETURN
      END

      SUBROUTINE CHARMMNEB(XX,Q)
      IMPLICIT NONE
      DOUBLE PRECISION XX(*), Q(*)

      RETURN
      END

      SUBROUTINE REBUILDNEB(X,Y,Z)
      IMPLICIT NONE
      DOUBLE PRECISION X(*),Y(*),Z(*)

      RETURN
      END

      SUBROUTINE REBUILDIMAGE(XX)
      IMPLICIT NONE
      DOUBLE PRECISION XX(*)

      RETURN
      END

      SUBROUTINE PURGICPHI(LENIC,B1IC,B2IC,T1IC,T2IC,PIC,
     A                  IAR,JAR,KAR,LAR,TAR,LFILL,LALL,LCLEAR,TYPE,NRES,
     A                  NATC,IAC,KCB,KCT,KCP,NCB,NCT,NCP,CBB,CTB,CPB,ATC,IBASE,RES,BUILDRING)
      IMPLICIT NONE

      INTEGER LENIC
      DOUBLE PRECISION B1IC(*),B2IC(*),T1IC(*),T2IC(*),PIC(*)
      INTEGER  IAR(*),JAR(*),KAR(*),LAR(*)
      LOGICAL TAR(*)
      LOGICAL LFILL,LALL,LCLEAR
      INTEGER NATC,NRES
      INTEGER IAC(*),IBASE(*)
      INTEGER KCB(*),KCT(*),KCP(*),NCB,NCT,NCP
      DOUBLE PRECISION CBB(*),CTB(*),CPB(*)
      CHARACTER(LEN=4) ATC(*),TYPE(*),RES(*)
      LOGICAL BUILDRING

      RETURN
      END

      SUBROUTINE CHECKPOINT(XX,FAILCHECK)
      IMPLICIT NONE
      DOUBLE PRECISION XX(*)
      LOGICAL FAILCHECK

      RETURN
      END

      SUBROUTINE CHECKICPHI(LENIC,B1IC,B2IC,T1IC,T2IC,PIC,
     A                  IAR,JAR,KAR,LAR,TAR,LFILL,LALL,LCLEAR,TYPE,NRES,
     A                  NATC,IAC,KCB,KCT,KCP,NCB,NCT,NCP,CBB,CTB,CPB,ATC,IBASE,RES,FAILCHECK)
      IMPLICIT NONE
      INTEGER LENIC
      DOUBLE PRECISION B1IC(*),B2IC(*),T1IC(*),T2IC(*),PIC(*)
      INTEGER  IAR(*),JAR(*),KAR(*),LAR(*)
      LOGICAL TAR(*)
      LOGICAL LFILL,LALL,LCLEAR
      INTEGER NATC,NRES
      INTEGER IAC(*),IBASE(*)
      INTEGER KCB(*),KCT(*),KCP(*),NCB,NCT,NCP
      DOUBLE PRECISION CBB(*),CTB(*),CPB(*)
      CHARACTER(LEN=4) ATC(*),TYPE(*),RES(*)
      LOGICAL FAILCHECK

      RETURN
      END

      SUBROUTINE CHARMMDUMP(COORDS,FNAMEF)
      IMPLICIT NONE
      CHARACTER(LEN=*)  FNAMEF
      DOUBLE PRECISION COORDS(*)

      RETURN
      END

      SUBROUTINE CHARMMDUMP3(COORDS)
      IMPLICIT NONE
      DOUBLE PRECISION COORDS(*)

      RETURN
      END

      SUBROUTINE NEWREAD(X,Y,Z,NATOMS)
      IMPLICIT NONE

      INTEGER NATOMS
      DOUBLE PRECISION X(NATOMS),Y(NATOMS),Z(NATOMS)

      RETURN
      END

      SUBROUTINE CHARMMDUMP2(COORDS,IUNIT)
      IMPLICIT NONE
      INTEGER IUNIT
      DOUBLE PRECISION COORDS(*)

      RETURN
      END

      SUBROUTINE CHARMMDUMPMOBCAL(COORDS,FNAMEF)
      IMPLICIT NONE
      CHARACTER(LEN=*)  FNAMEF
      DOUBLE PRECISION COORDS(*)

      RETURN
      END

      SUBROUTINE OCHARMM(CART,GRAD,EREAL,GRADT)
      IMPLICIT NONE
      DOUBLE PRECISION CART(*), GRAD(*), EREAL
      LOGICAL GRADT

      RETURN
      END

      SUBROUTINE CHSETZSYMATMASS
      IMPLICIT NONE

      RETURN
      END

      SUBROUTINE GETETERM(EBOND,EANGLE,EUREYB,EDIHE,EIMDIHE,ENONBOND)
      IMPLICIT NONE
      DOUBLE PRECISION EBOND,EANGLE,EUREYB,EDIHE,EIMDIHE,ENONBOND

      RETURN
      END

      SUBROUTINE GETMAXAIM
      IMPLICIT NONE
      WRITE(*,*)'dummy GETMAXAIM> input.crd file present but the executable is not CGMIN - stopping'
      WRITE(*,*)'dummy GETMAXAIM> Please consult the Makefile, recompile and rerun'
      STOP

      RETURN
      END

      SUBROUTINE CHALLOCATE(NATOMS)
      IMPLICIT NONE
      INTEGER :: NATOMS

      RETURN
      END 

      SUBROUTINE CHSETDIHE
      IMPLICIT NONE

      RETURN
      END

      SUBROUTINE CHSETSEED
      IMPLICIT NONE

      RETURN
      END

      SUBROUTINE ICCHECKPP(LPHIPSI,LOMEGAC,LSIDECHAIN,LCHIRAL,IICD,LENIC,INTLEN,
     &  IUNIC,TYPE,IBASE,SEGID,RESID,NICTOT,NSEG,RES,NATOM,NRES,ISLCT,
     &  B1IC,B2IC,T1IC,T2IC,PIC,IAR,JAR,KAR,LAR,TAR)
      IMPLICIT NONE
      LOGICAL LPHIPSI,LOMEGAC,LSIDECHAIN,LCHIRAL
      INTEGER IICD
      INTEGER LENIC,INTLEN,IUNIC
      CHARACTER(LEN=4) SEGID(*),RESID(*),TYPE(*),RES(*)
      INTEGER IBASE(*),NICTOT(*)
      INTEGER NSEG,NATOM,NRES,ISLCT(*)
      DOUBLE PRECISION B1IC(*),B2IC(*),T1IC(*),T2IC(*),PIC(*)
      INTEGER  IAR(*),JAR(*),KAR(*),LAR(*)
      LOGICAL TAR(*)

      RETURN
      END

      INTEGER FUNCTION GETATOMN(ISEG,IRES,ATOM,TYPE,IBASE)
      IMPLICIT NONE
      CHARACTER(LEN=4) TYPE(*)
      INTEGER IBASE(*)
      CHARACTER*(*) ATOM
      INTEGER IRES,ISEG

      GETATOMN=0

      RETURN
      END

      SUBROUTINE CHGUESSTS(Q,ITEST,PTEST,TWISTFRAC,GUESSFAIL,DISTPF)
      IMPLICIT NONE
      DOUBLE PRECISION DISTPF, Q(*)
      LOGICAL PTEST,ITEST,GUESSFAIL
      DOUBLE PRECISION    TWISTFRAC

      RETURN
      END

      SUBROUTINE FILLICT(X,Y,Z,PPSANGLE,LINTCOOR)
      IMPLICIT NONE
      DOUBLE PRECISION X(*),Y(*),Z(*),PPSANGLE(*)
      LOGICAL LINTCOOR

      RETURN
      END

      SUBROUTINE GETPPSANGLE(PPSANGLE,PIC)
      IMPLICIT NONE
      DOUBLE PRECISION PPSANGLE(*)
      DOUBLE PRECISION PIC(*)

      RETURN
      END

      SUBROUTINE PRINTDIHE(QPRINT,QPPSANGLE,NANGLE)
      IMPLICIT NONE
      DOUBLE PRECISION QPRINT(*)
      DOUBLE PRECISION QPPSANGLE(*)
      INTEGER NANGLE

      RETURN
      END

      SUBROUTINE DIHENEB(Q,FINISH,POINTS,OFFSET)
      IMPLICIT NONE
      DOUBLE PRECISION POINTS(*)
      INTEGER             OFFSET
      DOUBLE PRECISION Q(*),FINISH(*)

      RETURN
      END

      SUBROUTINE GETDIHEDIST(DIHEDIST,QA,QB,QC)
      IMPLICIT NONE
      DOUBLE PRECISION QA(*),QB(*),QC(*)
      DOUBLE PRECISION DIHEDIST

      RETURN
      END

      SUBROUTINE CHCALCNUMHB(NUMHB,QLOCAL,LNATIVE)
      IMPLICIT NONE
      INTEGER NUMHB
      DOUBLE PRECISION QLOCAL(*)
      LOGICAL LNATIVE

      RETURN
      END

      SUBROUTINE CHCALCHPDIST(HPDIST,QLOCAL)
      IMPLICIT NONE
      DOUBLE PRECISION QLOCAL(*), HPDIST

      RETURN
      END

      SUBROUTINE CONVERTIC
      IMPLICIT NONE

      RETURN
      END

      SUBROUTINE GETIPHI(IICD,IPHI,IP,JP,KP,LP,NPHI,IAR,JAR,KAR,LAR,TAR)
      IMPLICIT NONE
      INTEGER  IAR(*),JAR(*),KAR(*),LAR(*)
      INTEGER  IP(*),JP(*),KP(*),LP(*),NPHI
      LOGICAL TAR(*)
      INTEGER IICD,IPHI

      RETURN
      END

      SUBROUTINE CHCALCRGYR(RGYR,QLOCAL,LSELECT)
      IMPLICIT NONE
      DOUBLE PRECISION QLOCAL(*)
      DOUBLE PRECISION RGYR
      LOGICAL LSELECT

      RETURN
      END

      SUBROUTINE EDITRGYR(RG,NATOMS,X,Y,Z,W,AM,ISLCT,FACT,LMASS,LWEIG)
      IMPLICIT NONE
      INTEGER NATOMS
      DOUBLE PRECISION X(*),Y(*),Z(*),W(*)
      DOUBLE PRECISION AM(*)
      INTEGER ISLCT(*)
      DOUBLE PRECISION FACT, RG
      LOGICAL LMASS,LWEIG

      RETURN
      END

      SUBROUTINE CHCALCRMSD(RMSD,QLOCAL)
      IMPLICIT NONE
      DOUBLE PRECISION QLOCAL(*)
      DOUBLE PRECISION RMSD

      RETURN
      END

      SUBROUTINE CHCALCHELIX(HELIX,QLOCAL)
      IMPLICIT NONE
      DOUBLE PRECISION QLOCAL(*)
      INTEGER HELIX

      RETURN
      END

      SUBROUTINE CHECKCISTRANS(PLUS,MINUS,CISTRANST)
      IMPLICIT NONE
      DOUBLE PRECISION PLUS(*),MINUS(*)
      LOGICAL CISTRANST

      RETURN
      END

      SUBROUTINE CHSETUP(CHX,CHY,CHZ,CHMASS,NATOM)
      IMPLICIT NONE
      INTEGER NATOM
      DOUBLE PRECISION CHX(*), CHY(*), CHZ(*), CHMASS(*)

      RETURN
      END

      SUBROUTINE GETKD(KD)
      IMPLICIT NONE
      INTEGER KD

      RETURN
      END

      SUBROUTINE GETNINT(NINTC)
      IMPLICIT NONE
      INTEGER NINTC
 
      RETURN
      END
 
      SUBROUTINE GETNNZ(NNZ)
      IMPLICIT NONE
      INTEGER NNZ
 
      RETURN
      END
      
      SUBROUTINE CHRESTOATOM(FROZENRES,FROZEN)
      IMPLICIT NONE
      LOGICAL FROZENRES(*),FROZEN(*)

      RETURN
      END
      
      SUBROUTINE TRANSFORM(XCART,GCART,XINT,GINT,NINTC,NCART,NNZ,NOCOOR,KD)
      IMPLICIT NONE
      INTEGER NINTC,NCART,NNZ,KD
      LOGICAL NOCOOR
      DOUBLE PRECISION XCART(*),GCART(*),XINT(*),GINT(*)

      RETURN
      END

      SUBROUTINE TRANSBACK(XINT,OLDQ,CART,NINTC,NCART,NNZ,KD)
      IMPLICIT NONE
      INTEGER NINTC,NCART,NNZ,KD
      DOUBLE PRECISION CART(*),XINT(*),OLDQ(*)

      RETURN
      END

      SUBROUTINE TRANSBACKDELTA(X,CARTX,COORDS,NINTC,NCART,NNZ,KD,FAILED,PTEST,EPSILON)
      IMPLICIT NONE
      INTEGER NINTC,NCART,NNZ,KD
      DOUBLE PRECISION CARTX(*),X(*),COORDS(*),EPSILON
      LOGICAL FAILED,PTEST

      RETURN
      END
  
      SUBROUTINE CHSETSEG
      RETURN
      END

      SUBROUTINE newconf(NP,NR)
      INTEGER NP,NR
      RETURN
      END

      SUBROUTINE mkrigidtrans(NP)
      INTEGER NP
      RETURN
      END

      SUBROUTINE mkrigidrot(NP)
      INTEGER NP
      RETURN
      END

      SUBROUTINE chrms(NP,RMSD)
      INTEGER NP
      DOUBLE PRECISION RMSD
      RETURN
      END

      SUBROUTINE saverms(NP,EPOT,RMSD)
      INTEGER NP
      DOUBLE PRECISION RMSD, EPOT
      RETURN
      END

      SUBROUTINE CHCALCDIHE(DIHE,QLOCAL)
      IMPLICIT NONE
      DOUBLE PRECISION DIHE,QLOCAL(*)
      RETURN
      END

      SUBROUTINE order_sasa(Solv_Acc_Area,RPRO,X,Y,Z)
      IMPLICIT NONE
      DOUBLE PRECISION Solv_Acc_Area,RPRO,X(*),Y(*),Z(*)
      RETURN
      END

      SUBROUTINE FixedEndMove(NP)
      IMPLICIT NONE
      INTEGER NP
      RETURN
      END

      SUBROUTINE CHCALCEINT(EINT,X,Y,Z)
      IMPLICIT NONE
      DOUBLE PRECISION EINT,X(*),Y(*),Z(*) 
      RETURN
      END

      SUBROUTINE UPDATENBONDS(CART)
      IMPLICIT NONE
      DOUBLE PRECISION CART(*)
      RETURN
      END

      SUBROUTINE CHECKCHIRAL(QLOCAL,CHIRALFAIL)
      REAL*8  QLOCAL(*)
      LOGICAL CHIRALFAIL
      END

      SUBROUTINE CHECKOMEGA(QLOCAL,AMIDEFAIL)
      REAL*8  QLOCAL(*)
      LOGICAL AMIDEFAIL
      END

      SUBROUTINE CHMD(NP)
      INTEGER NP
      RETURN
      END
      
      SUBROUTINE CHMAKEOLIGOMER(NP)
      INTEGER NP
      RETURN
      END

      SUBROUTINE CHSETPROB
      IMPLICIT NONE
      RETURN
      END
  
      SUBROUTINE CHSECPRED
      IMPLICIT NONE
      RETURN
      END

      SUBROUTINE CHROTMOVE(NP)
      INTEGER NP
      RETURN
      END

      SUBROUTINE CAMSHIFTREAD(NAA)
      INTEGER NAA
      RETURN
      END
