SUBROUTINE GMIN_QUIP_WRAPPER(COORDS,GRADIENT,ENRG,QATOMTYPE,QARGSTR)

IMPLICIT NONE

DOUBLE PRECISION, DIMENSION(*) :: COORDS
DOUBLE PRECISION, DIMENSION(*) :: GRADIENT
DOUBLE PRECISION :: ENRG
CHARACTER(LEN=10240)  :: QARGSTR
CHARACTER(LEN=3) :: QATOMTYPE

RETURN

END SUBROUTINE GMIN_QUIP_WRAPPER
