!  GMIN: A program for finding global minima
!  Copyright (C) 1999-2006 David J. Wales
!  This file is part of GMIN.
!
!  GMIN is free software; you can redistribute it and/or modify
!  it under the terms of the GNU General Public License as published by
!  the Free Software Foundation; either version 2 of the License, or
!  (at your option) any later version.
!
!  GMIN is distributed in the hope that it will be useful,
!  but WITHOUT ANY WARRANTY; without even the implied warranty of
!  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!  GNU General Public License for more details.
!
!  You should have received a copy of the GNU General Public License
!  along with this program; if not, write to the Free Software
!  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
!

MODULE MODCHARMM
   IMPLICIT NONE
   SAVE

      INTEGER, DIMENSION(:), ALLOCATABLE  :: NPHIPSI,NOMEGAC,NSIDECHAIN,NCHIRAL  
      INTEGER, DIMENSION(:), ALLOCATABLE :: PHIPSI,OMEGAC,SIDECHAIN,CHIRAL  
      INTEGER, DIMENSION(:,:), ALLOCATABLE :: LOOPR
      INTEGER :: CHARMMTYPE, CHSEEDI, CHSEEDJ, CHSEEDK, CHFREQBB, CHFREQSC    
      INTEGER :: CHMDFREQ, CHFREQ, FTRANS, FROT, RMSSAVE, NEWCONFST, ACEUPSTEP, NLOOP
      LOGICAL :: TOMEGAC,TSIDECHAIN     ! CHARMMTWIST
      LOGICAL :: DAESTAT, OMEGAT, NEWCONFT, SELECTT, ACESOLV, SECPREDT, CHMOVET
      LOGICAL :: CHSTANDARDT, CHLOOPMODT, CHCLUSTERT, CHBBT, CHSCT, CHCARTMOVET, CHNEIGHBOURT
      LOGICAL :: OSASAT, ODIHET, ORMSDT, ONNHBT, ONHBT, ORGYT, OHYDRGYT, OEINTT
      DOUBLE PRECISION, DIMENSION(:,:), ALLOCATABLE :: CHPBB,CHPOM,CHPSC
      DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: REFCOORD,COORCOMP,REFPPSANGLE   ! CHREF
      INTEGER  :: REFNHB
      INTEGER  :: MON1(2),MON2(2)
      DOUBLE PRECISION :: MYCUTHB,MYCUTHBA
      INTEGER, ALLOCATABLE, DIMENSION(:) :: REFIHB,REFJHB,REFKHB
      DOUBLE PRECISION :: CHPMIN, CHPMAX, CHNMIN, CHNMAX
      DOUBLE PRECISION :: PTRANS,PROT,TRANSMAX,ROTMAX,RMSLIMIT,RMSTOL,NCWALL,BOXSIZE,SPHERERAD
      INTEGER :: ISEED, NCHENCALLS, NREPEAT, NKNOWN, NFIXSEG
      LOGICAL :: GCHARMMFAIL,CHRIGIDTRANST, CHRIGIDROTT, BOXT, RMST, SPHERET, CHMDT
      LOGICAL :: MAKEOLIGOT, MAKEOLIGOSTART, INITROT, TRANSXYT, ROTZT
      DOUBLE PRECISION :: PLACERMIN, PLACERMAX
      DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:) :: REPPHIF, REPPHIL 
      INTEGER, ALLOCATABLE, DIMENSION(:) :: NSEGATOMS, REPATF, REPATL     
      LOGICAL, ALLOCATABLE, DIMENSION(:) :: SEGMENTT
      DOUBLE PRECISION :: PIVOTP, SIDECHAINP
      DOUBLE PRECISION, ALLOCATABLE, DIMENSION(:,:) :: RMSBEST,RMSCOOR 
      DOUBLE PRECISION :: RPRO, STEPBOND, STEPANGLE, STEPDIHE
      CHARACTER(LEN=500) :: CHMDPAR,CHSEC
      CHARACTER(LEN=50) :: SECPREDFILE

END MODULE
