MODULE PREC

INTEGER, PARAMETER  :: INT32  = SELECTED_INT_KIND(9)
INTEGER, PARAMETER  :: INT64  = SELECTED_INT_KIND(18)
INTEGER, PARAMETER  :: REAL32 = SELECTED_REAL_KIND(6, 37)
INTEGER, PARAMETER  :: REAL64 = SELECTED_REAL_KIND(15, 307)

END MODULE PREC
