!   NEB module is an implementati on of the nudged elastic band method for performing double-ended pathway searches.
!   Copyright (C) 2003-2006 Semen A. Trygubenko and David J. Wales
!   This file is part of NEB module. NEB module is part of OPTIM.
!
!   OPTIM is free software; you can redistribute it and/or modify
!   it under the terms of the GNU General Public License as published by
!   the Free Software Foundation; either version 2 of the License, or
!   (at your option) any later version.
!
!   OPTIM is distributed in the hope that it will be useful,
!   but WITHOUT ANY WARRANTY; without even the implied warranty of
!   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!   GNU General Public License for more details.
!
!   You should have received a copy of the GNU General Public License
!   along with this program; if not, write to the Free Software
!   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
!
SUBROUTINE QCIPOT(ECON,XYZ,GGG)
USE COMMONS, ONLY: FROZEN, FREEZE, NREPI, NREPJ, NNREPULSIVE, &
  &            NCONSTRAINT, CONI, CONJ, INTCONSTRAINTDEL, INTCONSTRAINTREP, CONDISTREFLOCAL, &
  &            CONACTIVE, INTCONSTRAINREPCUT, NREPCUT, IMSEPMAX, &
  &            INTFREEZET, INTFROZEN, CONCUTLOCAL, CONCUTABST, CONCUTABS, CONCUTFRACT, CONCUTFRAC, &
  &  NATOMS, DEBUG, MYUNIT
USE PORFUNCS
IMPLICIT NONE
           
INTEGER :: J2,NI2,NI1,NJ2,NJ1
DOUBLE PRECISION :: ECON, EREP, RMS
DOUBLE PRECISION D2,R2AX,R2AY,R2AZ,R2BX,R2BY,R2BZ
DOUBLE PRECISION G2(3)
DOUBLE PRECISION DUMMY, REPGRAD(3), INTCONST, D12
DOUBLE PRECISION XYZ(3*NATOMS), GGG(3*NATOMS), CCLOCAL

GGG(1:3*NATOMS)=0.0D0
ECON=0.0D0; EREP=0.0D0
!
!  Constraint energy and forces.
!
! WRITE(MYUNIT,'(A,I8)') 'qcipot> NCONSTRAINT=',NCONSTRAINT
DO J2=1,NCONSTRAINT
!  WRITE(MYUNIT,'(A,I8,L5)') 'qcipot> J2,CONACTIVE=',J2,CONACTIVE(J2)
   IF (.NOT.CONACTIVE(J2)) CYCLE
   CCLOCAL=CONCUTLOCAL(J2)
   IF (CONCUTABST) CCLOCAL=CCLOCAL+CONCUTABS
   IF (CONCUTFRACT) CCLOCAL=CCLOCAL+CONCUTFRAC*CONDISTREFLOCAL(J2)
   NI1=3*(CONI(J2)-1)
   NJ1=3*(CONJ(J2)-1)
   R2AX=XYZ(NI1+1); R2AY=XYZ(NI1+2); R2AZ=XYZ(NI1+3)
   R2BX=XYZ(NJ1+1); R2BY=XYZ(NJ1+2); R2BZ=XYZ(NJ1+3)
   D2=SQRT((R2AX-R2BX)**2+(R2AY-R2BY)**2+(R2AZ-R2BZ)**2)
!  WRITE(MYUNIT,'(A,I8,3G20.10)') 'J2,D2,CONDISTREFLOCAL,CCLOCAL=',J2,D2,CONDISTREFLOCAL(J2),CCLOCAL
   IF (ABS(D2-CONDISTREFLOCAL(J2)).GT.CCLOCAL) THEN 
      DUMMY=D2-CONDISTREFLOCAL(J2)  
      G2(1)=(R2AX-R2BX)/D2
      G2(2)=(R2AY-R2BY)/D2
      G2(3)=(R2AZ-R2BZ)/D2
      REPGRAD(1:3)=2*INTCONSTRAINTDEL*((DUMMY/CCLOCAL)**2-1.0D0)*DUMMY*G2(1:3)
      DUMMY=INTCONSTRAINTDEL*(DUMMY**2-CCLOCAL**2)**2/(2.0D0*CCLOCAL**2)
      ECON=ECON        +DUMMY
!     WRITE(MYUNIT,'(A,I8,2G20.10)') 'J2,DUMMY,ECON=',J2,DUMMY,ECON
      GGG(NI1+1:NI1+3)=GGG(NI1+1:NI1+3)+REPGRAD(1:3)
      GGG(NJ1+1:NJ1+3)=GGG(NJ1+1:NJ1+3)-REPGRAD(1:3)
!     WRITE(MYUNIT,'(A,6G20.10)') 'con grads=',GGG(NI1+1:NI1+3),GGG(NJ1+1:NJ1+3)
   ENDIF
ENDDO

DO J2=1,NNREPULSIVE
   INTCONST=NREPCUT(J2)**3
   NI2=3*(NREPI(J2)-1)
   NJ2=3*(NREPJ(J2)-1)
   R2AX=XYZ(NI2+1); R2AY=XYZ(NI2+2); R2AZ=XYZ(NI2+3)
   R2BX=XYZ(NJ2+1); R2BY=XYZ(NJ2+2); R2BZ=XYZ(NJ2+3)
   D2=SQRT((R2AX-R2BX)**2+(R2AY-R2BY)**2+(R2AZ-R2BZ)**2)
   IF (D2.LT.NREPCUT(J2)) THEN ! term for image J1
!     D12=D2**12
      D12=D2**2
!     DUMMY=INTCONSTRAINTREP*(1.0D0/D12+(12.0D0*D2-13.0D0*NREPCUT(J2))/INTCONST)
      DUMMY=INTCONSTRAINTREP*(1.0D0/D12+(2.0D0*D2-3.0D0*NREPCUT(J2))/INTCONST)
!     WRITE(MYUNIT,'(A,I8,2G20.10)') 'J2,DUMMY,EREP=',J2,DUMMY,EREP
      EREP=EREP+DUMMY
!     DUMMY=-12.0D0*INTCONSTRAINTREP*(1.0D0/(D2*D12)-1.0D0/INTCONST)
      DUMMY=-2.0D0*INTCONSTRAINTREP*(1.0D0/(D2*D12)-1.0D0/INTCONST)
      G2(1)=(R2AX-R2BX)/D2
      G2(2)=(R2AY-R2BY)/D2
      G2(3)=(R2AZ-R2BZ)/D2
      REPGRAD(1:3)=DUMMY*G2(1:3)
      GGG(NI2+1:NI2+3)=GGG(NI2+1:NI2+3)+REPGRAD(1:3)
      GGG(NJ2+1:NJ2+3)=GGG(NJ2+1:NJ2+3)-REPGRAD(1:3)
!     WRITE(MYUNIT,'(A,6G20.10)') 'rep grads=',GGG(NI2+1:NI2+3),GGG(NJ2+1:NJ2+3)
   ENDIF
ENDDO
!
! Set gradients on frozen atoms to zero.
!
IF (FREEZE) THEN
   DO J2=1,NATOMS
      IF (FROZEN(J2)) THEN
         GGG(3*(J2-1)+1)=0.0D0
         GGG(3*(J2-1)+2)=0.0D0
         GGG(3*(J2-1)+3)=0.0D0
      ENDIF
   ENDDO
ENDIF

END SUBROUTINE QCIPOT

SUBROUTINE CHECKREPQCIPOT(XYZ,NOPT,NNSTART,NSTART)
USE COMMONS,ONLY : NREPI, NREPJ, NREPCUT, NNREPULSIVE, NREPULSIVE, REPI, REPJ, REPCUT, CHECKREPCUTOFF, DEBUG, MYUNIT
USE PORFUNCS
IMPLICIT NONE
INTEGER JJ, NOPT, NI, NJ, NNSTART, NSTART
DOUBLE PRECISION LDIST, XYZ(NOPT),COMPARE

NNREPULSIVE=NNSTART
DO JJ=NSTART,NREPULSIVE
   COMPARE=(CHECKREPCUTOFF*REPCUT(JJ))**2
   NI=REPI(JJ)
   NJ=REPJ(JJ)
   LDIST=(XYZ(3*(NI-1)+1)-XYZ(3*(NJ-1)+1))**2 &
  &     +(XYZ(3*(NI-1)+2)-XYZ(3*(NJ-1)+2))**2 &
  &     +(XYZ(3*(NI-1)+3)-XYZ(3*(NJ-1)+3))**2
   IF (LDIST.LT.COMPARE) THEN
      NNREPULSIVE=NNREPULSIVE+1
      NREPI(NNREPULSIVE)=NI
      NREPJ(NNREPULSIVE)=NJ
      NREPCUT(NNREPULSIVE)=REPCUT(JJ)
      GOTO 246
   ENDIF
   COMPARE=CHECKREPCUTOFF*REPCUT(JJ)
246 CONTINUE
ENDDO
IF (DEBUG) WRITE(MYUNIT,'(A,2I8)') ' checkrep> number of active repulsions and total=',NNREPULSIVE,NREPULSIVE

END SUBROUTINE CHECKREPQCIPOT

!
! QCI potential with no flat region for constraints.
!
SUBROUTINE QCIPOT2(ECON,XYZ,GGG)
USE COMMONS, ONLY: FROZEN, FREEZE, NREPI, NREPJ, NNREPULSIVE, &
  &            NCONSTRAINT, CONI, CONJ, INTCONSTRAINTDEL, INTCONSTRAINTREP, CONDISTREFLOCAL, &
  &            CONACTIVE, INTCONSTRAINREPCUT, NREPCUT, IMSEPMAX, &
  &            INTFREEZET, INTFROZEN, CONCUTLOCAL, CONCUTABST, CONCUTABS, CONCUTFRACT, CONCUTFRAC, &
  &  NATOMS, DEBUG, MYUNIT
USE PORFUNCS
IMPLICIT NONE
           
INTEGER :: J2,NI2,NI1,NJ2,NJ1
DOUBLE PRECISION :: ECON, EREP, RMS
DOUBLE PRECISION D2,R2AX,R2AY,R2AZ,R2BX,R2BY,R2BZ
DOUBLE PRECISION G2(3)
DOUBLE PRECISION DUMMY, REPGRAD(3), INTCONST, D12
DOUBLE PRECISION XYZ(3*NATOMS), GGG(3*NATOMS), CCLOCAL

GGG(1:3*NATOMS)=0.0D0
ECON=0.0D0; EREP=0.0D0
!
!  Constraint energy and forces.
!
! WRITE(MYUNIT,'(A,I8)') 'qcipot> NCONSTRAINT=',NCONSTRAINT
DO J2=1,NCONSTRAINT
!  WRITE(MYUNIT,'(A,I8,L5)') 'qcipot> J2,CONACTIVE=',J2,CONACTIVE(J2)
   IF (.NOT.CONACTIVE(J2)) CYCLE
!  CCLOCAL=CONCUTLOCAL(J2)
!  IF (CONCUTABST) CCLOCAL=CCLOCAL+CONCUTABS
!  IF (CONCUTFRACT) CCLOCAL=CCLOCAL+CONCUTFRAC*CONDISTREFLOCAL(J2)
   NI1=3*(CONI(J2)-1)
   NJ1=3*(CONJ(J2)-1)
   R2AX=XYZ(NI1+1); R2AY=XYZ(NI1+2); R2AZ=XYZ(NI1+3)
   R2BX=XYZ(NJ1+1); R2BY=XYZ(NJ1+2); R2BZ=XYZ(NJ1+3)
   D2=SQRT((R2AX-R2BX)**2+(R2AY-R2BY)**2+(R2AZ-R2BZ)**2)
!  WRITE(MYUNIT,'(A,I8,3G20.10)') 'J2,D2,CONDISTREFLOCAL,CCLOCAL=',J2,D2,CONDISTREFLOCAL(J2),CCLOCAL
   DUMMY=D2-CONDISTREFLOCAL(J2)  
   G2(1)=(R2AX-R2BX)/D2
   G2(2)=(R2AY-R2BY)/D2
   G2(3)=(R2AZ-R2BZ)/D2
   REPGRAD(1:3)=2*INTCONSTRAINTDEL*DUMMY**2*DUMMY*G2(1:3)
   DUMMY=INTCONSTRAINTDEL*DUMMY**4/2.0D0
   ECON=ECON        +DUMMY
!  WRITE(MYUNIT,'(A,I8,2G20.10)') 'J2,DUMMY,ECON=',J2,DUMMY,ECON
   GGG(NI1+1:NI1+3)=GGG(NI1+1:NI1+3)+REPGRAD(1:3)
   GGG(NJ1+1:NJ1+3)=GGG(NJ1+1:NJ1+3)-REPGRAD(1:3)
!  WRITE(MYUNIT,'(A,6G20.10)') 'con grads=',GGG(NI1+1:NI1+3),GGG(NJ1+1:NJ1+3)
ENDDO

DO J2=1,NNREPULSIVE
   INTCONST=NREPCUT(J2)**3
   NI2=3*(NREPI(J2)-1)
   NJ2=3*(NREPJ(J2)-1)
   R2AX=XYZ(NI2+1); R2AY=XYZ(NI2+2); R2AZ=XYZ(NI2+3)
   R2BX=XYZ(NJ2+1); R2BY=XYZ(NJ2+2); R2BZ=XYZ(NJ2+3)
   D2=SQRT((R2AX-R2BX)**2+(R2AY-R2BY)**2+(R2AZ-R2BZ)**2)
   IF (D2.LT.NREPCUT(J2)) THEN ! term for image J1
!     D12=D2**12
      D12=D2**2
!     DUMMY=INTCONSTRAINTREP*(1.0D0/D12+(12.0D0*D2-13.0D0*NREPCUT(J2))/INTCONST)
      DUMMY=INTCONSTRAINTREP*(1.0D0/D12+(2.0D0*D2-3.0D0*NREPCUT(J2))/INTCONST)
!     WRITE(MYUNIT,'(A,I8,2G20.10)') 'J2,DUMMY,EREP=',J2,DUMMY,EREP
      EREP=EREP+DUMMY
!     DUMMY=-12.0D0*INTCONSTRAINTREP*(1.0D0/(D2*D12)-1.0D0/INTCONST)
      DUMMY=-2.0D0*INTCONSTRAINTREP*(1.0D0/(D2*D12)-1.0D0/INTCONST)
      G2(1)=(R2AX-R2BX)/D2
      G2(2)=(R2AY-R2BY)/D2
      G2(3)=(R2AZ-R2BZ)/D2
      REPGRAD(1:3)=DUMMY*G2(1:3)
      GGG(NI2+1:NI2+3)=GGG(NI2+1:NI2+3)+REPGRAD(1:3)
      GGG(NJ2+1:NJ2+3)=GGG(NJ2+1:NJ2+3)-REPGRAD(1:3)
!     WRITE(MYUNIT,'(A,6G20.10)') 'rep grads=',GGG(NI2+1:NI2+3),GGG(NJ2+1:NJ2+3)
   ENDIF
ENDDO
!
! Set gradients on frozen atoms to zero.
!
IF (FREEZE) THEN
   DO J2=1,NATOMS
      IF (FROZEN(J2)) THEN
         GGG(3*(J2-1)+1)=0.0D0
         GGG(3*(J2-1)+2)=0.0D0
         GGG(3*(J2-1)+3)=0.0D0
      ENDIF
   ENDDO
ENDIF

END SUBROUTINE QCIPOT2
