
SUBROUTINE READ_CMD_ARGS

USE PORFUNCS
USE COMMONS,ONLY : INFILE

IMPLICIT NONE

INTEGER NARGS, I
CHARACTER(LEN=80) BFF

! EXTERNAL DISPLAY_VERSION

CALL IARGC_SUBR(NARGS)    
I=0

IF (NARGS.GT.0) THEN 
  DO WHILE(I.LT.NARGS) ; I=I+1 ; CALL GETARG_SUBR(I,BFF)
     SELECTCASE(BFF)
       CASE('-v') 
         CALL DISPLAY_VERSION(0)
         STOP
       CASE('-t')
         I=I+1
         CALL GETARG_SUBR(I,BFF)
         !CALL MAKETEST(BFF)
       CASE DEFAULT
         INFILE=TRIM(ADJUSTL(BFF))
     ENDSELECT
  ENDDO
ENDIF

END SUBROUTINE READ_CMD_ARGS
